services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: pirate_team
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pirate_team"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pirate-net          # ← добавить

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pirate_team
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pirate-net          # ← добавить

volumes:
  postgres_data:

networks:
  pirate-net:               # ← добавить