ALTER TABLE team
    ADD COLUMN fleet_id   UUID,
    ADD COLUMN morale     INT NOT NULL DEFAULT 50,
    ADD COLUMN loyalty    INT NOT NULL DEFAULT 50,
    ADD COLUMN loot_bonus INT NOT NULL DEFAULT 0,
    ADD COLUMN power      INT NOT NULL DEFAULT 0,
    ADD COLUMN fatigue    INT NOT NULL DEFAULT 0;