ALTER TABLE pirate
    ALTER COLUMN created_at TYPE TIMESTAMP USING created_at::TIMESTAMP,
    ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at::TIMESTAMP;

ALTER TABLE pirate
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;